### ISSUE TITLE
ErNamedClass.java:35-38: Annotations to skip rule. It is...

### ISSUE THREAD

**Issue by 0pdd** [l3r8yJ/oop-cop#97] opened 2023-12-30 00:26 UTC
The puzzle `35-ba2ad0f0` from #35 has to be resolved: 

https://github.com/l3r8yJ/oop-cop/blob/2bee691998f31382e5652681bc9421e18c122ee0/src/main/java/ru/l3r8y/rule/ErNamedClass.java#L35-L38

The puzzle was created by @h1alexbel on 29-Dec-23. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by zoeself** [comment] 2023-12-30 00:26
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment] 2023-12-30 00:26
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by zoeself** [comment] 2023-12-30 00:30
@l3r8yJ this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-09T00:30:28.150702``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by l3r8yJ** [comment] 2023-12-31 10:11
@h1alexbel can you help us here?

**Comment by h1alexbel** [comment] 2024-01-01 15:39
@l3r8yJ yes, assign me on it

**Comment by l3r8yJ** [comment] 2024-01-01 17:08
@zoeself reasign

**Comment by zoeself** [comment] 2024-01-01 17:09
> @zoeself reasign 

@l3r8yJ didn't understand that, sorry.

**Comment by l3r8yJ** [comment] 2024-01-01 17:19
@zoeself resign

**Comment by zoeself** [comment] 2024-01-01 17:19
> @zoeself resign 

@l3r8yJ ok, I'll find someone else to take care of it.

**Comment by zoeself** [comment] 2024-01-01 17:20
@h1alexbel this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2024-01-11T17:20:06.961013``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by h1alexbel** [comment] 2024-01-03 06:55
@l3r8yJ its a duplicate of #38, let's close it

**Comment by l3r8yJ** [comment] 2024-01-03 14:06
sure

**Closed by l3r8yJ** 2024-01-03 14:06 UTC
Labels: @h1alexbel
